name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print Hostname
        run: hostname
      - name: Show Current Directory
        run: pwd
      - name: List Files
        run: ls -la

